function dWdxi = dFitness(xi, ubar, xbar, k, epsil, bmax, ...
    cost, kappa)
% A function to compute the partial derivative with respect to 
% xi_m of the fitness function; ubar and xbar are the 
% equilibrium values of u and x, respectively.
dWdxi = (1/(2*sqrt(k^2*(kappa + xi)^2*cost^2 - 2*k*ubar*xi*bmax*...
    (kappa + xi)*(epsil^2*xbar - 1)*cost + ubar^2*xi^2*bmax^2*...
    (epsil^2*xbar - 2*xbar*epsil + 1)^2)*(1 + xi)^2*(kappa ...
    + xi)^2))*(-(((ubar*(epsil^2*xbar - 2*xbar*epsil + 1)*bmax ...
    - k*cost)*xi^2 - 2*cost*k*kappa*xi - (ubar*(epsil^2*xbar ...
    - 2*xbar*epsil + 1)*bmax + k*kappa*cost)*kappa)*...
    sqrt(k^2*(kappa + xi)^2*cost^2 - 2*k*ubar*xi*bmax*(kappa ...
    + xi)*(epsil^2*xbar - 1)*cost + ubar^2*xi^2*bmax^2*...
    (epsil^2*xbar - 2*xbar*epsil + 1)^2) + (ubar^2*bmax^2*...
    (epsil^2*xbar - 2*xbar*epsil + 1)^2 - 2*k*ubar*cost*...
    (epsil^2*xbar - 1)*bmax + cost^2*k^2)*xi^3 + 3*k*cost*...
    ((-epsil^2*xbar + 1)*ubar*bmax + k*cost)*kappa*xi^2 ...
    + 3*(-(1/3)*ubar^2*bmax^2*(epsil^2*xbar - 2*xbar*epsil ...
    + 1)^2 - (1/3)*k*ubar*cost*(kappa - 1)*(epsil^2*xbar ...
    - 1)*bmax + cost^2*k^2*kappa)*kappa*xi + k*(ubar*bmax*...
    (epsil^2*xbar - 1) + k*kappa*cost)*cost*kappa^2));