function dres = resident(res, xi, k, epsil, bmax, ...
    cost, kappa)
% A function to define the resident (u, v, x, y) ODE 
% system; res is a vector of four entries representing 
% u, v, x, and y; other inputs are as detailed in the 
% model in the main paper.
dres = zeros(1, 4);
dres(1) = 1 - (b11(xi, epsil, bmax, kappa)*res(3)*...
    res(4) + b01(xi, epsil, bmax, kappa)*...
    (1 - res(3))*res(4) + b10(xi, epsil, ...
    bmax, kappa)*res(3)*(1 - res(4)) + ...
    b00(xi, bmax, kappa)*(1 - res(3))*...
    (1 - res(4)))*res(1)*res(2) - res(1);
dres(2) = (b11(xi, epsil, bmax, kappa)*res(3)*...
    res(4) + b01(xi, epsil, bmax, kappa)*...
    (1 - res(3))*res(4) + b10(xi, epsil, ...
    bmax, kappa)*res(3)*(1 - res(4)) +...
    b00(xi, bmax, kappa)*(1 - res(3))*...
    (1 - res(4)))*res(1)*res(2) - ...
    (1 + g(xi))*res(2);
dres(3) = -res(3)/res(1) + (k + 1)*res(3)*...
    (1 - res(3))*(res(4)*...
    (b01(xi, epsil, bmax, kappa) - ...
    b11(xi, epsil, bmax, kappa)) + (1 - res(4))*...
    (b00(xi, bmax, kappa) - ...
    b10(xi, epsil, bmax, kappa)))*res(2) ...
    - k*res(3)*cost;
dres(4) = (b11(xi, epsil, bmax, kappa)*res(3)*res(4)*...
    (1 - res(4)) - b01(xi, epsil, bmax, kappa)*...
    (1 - res(3))*(res(4))^2 + ...
    b10(xi, epsil, bmax, kappa)*res(3)*...
    (1 - res(4))^2 - b00(xi, bmax, kappa)*...
    (1 - res(3))*res(4)*(1 - res(4)))*res(1) - ...
    k*res(4)*cost;